### ISSUE TITLE
set_outpath issue in info.py Observation()

### ISSUE THREAD

**Issue by rmludlam** [NuSTAR/nustar-gen-utils#68]
The class Observation() in info.py has an issue with interpreting defined outpath. 

For example:

    here = os.getcwd()
    pathout=here+'/'+seqid[i]+'_SLproducts'
    print("Defined Outpath Location:", pathout)
    
    pathin=here+'/'+seqid[i]+'_reproc'
    print("Defined Event Directory Location:", pathin)
    
    obs = info.Observation(seqid=seqid[i], path=here, evdir=pathin, out_path=pathout)

Will return this error when run:

Traceback (most recent call last):
  File "/disk/bifrost/rmludlam/straycats/mkexpomap.py", line 52, in <module>
    obs = info.Observation(seqid=seqid[i], path=here, evdir=pathin, out_path=pathout)
  File "/disk/bifrost/rmludlam/nustar-gen-utils/nustar_gen/info.py", line 208, in __init__
    self._set_seqid(seqid)
  File "/disk/bifrost/rmludlam/nustar-gen-utils/nustar_gen/info.py", line 353, in _set_seqid
    self._set_datapath(os.path.join(self._path, self._seqid))
  File "/disk/bifrost/rmludlam/nustar-gen-utils/nustar_gen/info.py", line 246, in _set_datapath
    assert os.path.isdir(self._datapath), f"Output path does not exist! {self._datapath})"
AssertionError: Output path does not exist! /disk/bifrost/rmludlam/straycats/90201030002)

**Comment by bwgref** [comment]
Reproduced this locally. New version should fix it.
